blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/ScottsSecondAct/some/discussions
    about: Ask questions or start a discussion here (when Discussions is enabled).